// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// checkNested
std::string checkNested(const CharacterMatrix& groups, int L);
RcppExport SEXP _FastGxC_checkNested(SEXP groupsSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const CharacterMatrix& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(checkNested(groups, L));
    return rcpp_result_gen;
END_RCPP
}
// getGroupPvalues
NumericMatrix getGroupPvalues(const NumericVector& pvals, const CharacterMatrix& groups, int N, int L, CharacterVector test);
RcppExport SEXP _FastGxC_getGroupPvalues(SEXP pvalsSEXP, SEXP groupsSEXP, SEXP NSEXP, SEXP LSEXP, SEXP testSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type pvals(pvalsSEXP);
    Rcpp::traits::input_parameter< const CharacterMatrix& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type test(testSEXP);
    rcpp_result_gen = Rcpp::wrap(getGroupPvalues(pvals, groups, N, L, test));
    return rcpp_result_gen;
END_RCPP
}
// getGroupSelections
NumericMatrix getGroupSelections(const NumericMatrix& group_pvals, const CharacterMatrix& groups, const NumericVector& q, int N, int L);
RcppExport SEXP _FastGxC_getGroupSelections(SEXP group_pvalsSEXP, SEXP groupsSEXP, SEXP qSEXP, SEXP NSEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type group_pvals(group_pvalsSEXP);
    Rcpp::traits::input_parameter< const CharacterMatrix& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type q(qSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(getGroupSelections(group_pvals, groups, q, N, L));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastGxC_checkNested", (DL_FUNC) &_FastGxC_checkNested, 2},
    {"_FastGxC_getGroupPvalues", (DL_FUNC) &_FastGxC_getGroupPvalues, 5},
    {"_FastGxC_getGroupSelections", (DL_FUNC) &_FastGxC_getGroupSelections, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastGxC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
