# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Check if groups are properly nested in hierarchy
checkNested <- function(groups, L) {
    .Call(`_FastGxC_checkNested`, groups, L)
}

#' Hierarchical Group P-value Calculation
#' The getGroupPvalues function computes aggregated p-values for each group in a hierarchical 
#' structure by combining p-values from lower levels using specified aggregation methods.
#' @param pvals NumericVector containing p-values for individual hypotheses
#' @param groups CharacterMatrix defining the group hierarchy structure
#' @param N Integer specifying the number of hypotheses
#' @param L Integer specifying the number of levels in the hierarchy
#' @param test CharacterVector specifying the aggregation method(s)
getGroupPvalues <- function(pvals, groups, N, L, test) {
    .Call(`_FastGxC_getGroupPvalues`, pvals, groups, N, L, test)
}

#' Hierarchical Group Selection for Multiple Testing
#' The getGroupSelections function applies hierarchical multiple testing correction.
#' @param group_pvals NumericMatrix containing aggregated p-values
#' @param groups CharacterMatrix defining the group hierarchy structure
#' @param q NumericVector containing the q-value thresholds for each level
#' @param N Integer specifying the number of hypotheses
#' @param L Integer specifying the number of levels in the hierarchy
getGroupSelections <- function(group_pvals, groups, q, N, L) {
    .Call(`_FastGxC_getGroupSelections`, group_pvals, groups, q, N, L)
}

